[s3]
# endpoint   = "s3.test.com"
# accessKey  = "hehehehe"
# secretKey  = "hehehehe"
# bucketName = "go-sdk-test"
# objectKey = "go-sdk-key"
# localFilePath = "sample/L.jpeg"
endpoint   = "oss-cn-north-2.unicloudsrv.com"
accessKey  = "DrjUiXNcQXih3R5n"
secretKey  = "dqcLTLYnczosouL1v7ZEC7buM8hm1b"
bucketName = "zztet123"
objectKey = "test"
localFilePath = "sample/L.jpeg"